python -m parlai.scripts.train_model -t opensubtitles -dt train:stream -m transformer/generator_septoken \
-mf ./checkpoints/transformer-opensubtitles-1 \
--init_model ./checkpoints/transformer-opensubtitles.checkpoint \
--dict-tokenizer bpe --dict-lower True --dict-septoken __sep__ --person-tokens True --add-p1-after-newln True --history-add-global-end-token end \
--n_positions=512 --truncate=128 \
--inference beam --beam-size 7 \
--embedding-size 512 --n_heads 8 --n_layers 6 --ffn_size 2048 --activation gelu --tie_layers \
--dropout 0.15 --attention-dropout 0.15 \
--num-epochs 2 -veps 0.01 -vme 512 -vmt ppl -vmm min -sval True \
-bs 128 --optimizer mem_eff_adam -lr 5e-5 --update_freq 1 \
--warmup_updates 8000 --lr-scheduler-patience 200 --lr-scheduler-decay 0.2 -vp 500 \
-tblog True --fp16 True --fp16-impl mem_efficient --dict-extratokens 7 --dynamic_batching batchsort --evaltask convai2
